### ISSUE TITLE
src/storage/storage.cc:119: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error

### ISSUE THREAD

**Issue by phoenixbai** [samsungsds-rnd/deepspeech.mxnet#17]
I run below command, and it throws error as follow:
`python main.py --configfile default.cfg`

> [    INFO][2018/05/18 17:42:58.046] load_optimizer_states = True
[    INFO][2018/05/18 17:42:58.046] is_start_from_batch = False
[    INFO][2018/05/18 17:42:58.046]
[    INFO][2018/05/18 17:42:58.047] [optimizer]
[    INFO][2018/05/18 17:42:58.047] optimizer = adam
[    INFO][2018/05/18 17:42:58.047] optimizer_params_dictionary = {"beta1":0.9,"beta2":0.999}
[    INFO][2018/05/18 17:42:58.047] clip_gradient = 0
[    INFO][2018/05/18 17:42:58.047] weight_decay = 0.
[    INFO][2018/05/18 17:42:58.047]
Traceback (most recent call last):
  File "main.py", line 305, in <module>
    do_training(args=args, module=module, data_train=data_train, data_val=data_val)
  File "/gruntdata/zhimo.bmz/deepspeech.mxnet/train.py", line 93, in do_training
    for_training=True)
  File "/gruntdata/zhimo.bmz/mxnet/python/mxnet/module/module.py", line 430, in bind
    state_names=self._state_names)
  File "/gruntdata/zhimo.bmz/mxnet/python/mxnet/module/executor_group.py", line 265, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/gruntdata/zhimo.bmz/mxnet/python/mxnet/module/executor_group.py", line 361, in bind_exec
    shared_group))
  File "/gruntdata/zhimo.bmz/mxnet/python/mxnet/module/executor_group.py", line 639, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/gruntdata/zhimo.bmz/mxnet/python/mxnet/symbol/symbol.py", line 1524, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (2, 393, 161)
forward_l0_init_h: (2, 1760)
backward_l0_init_h: (2, 1760)
label: (2, 53)
[17:42:58] src/storage/storage.cc:119: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error

>Stack trace returned 10 entries:
[bt] (0) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::StackTrace()+0x4a) [0x7fc1be6dce0a]
[bt] (1) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x21) [0x7fc1be6dd411]
[bt] (2) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(+0x35cf6f0) [0x7fc1c103f6f0]
[bt] (3) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(+0x35d03d9) [0x7fc1c10403d9]
[bt] (4) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::StorageImpl::Alloc(mxnet::Storage::Handle*)+0x3f) [0x7fc1c10417bf]
[bt] (5) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(+0x301a753) [0x7fc1c0a8a753]
[bt] (6) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::exec::InitZeros(mxnet::NDArrayStorageType, nnvm::TShape const&, mxnet::Context const&, int)+0x3d) [0x7fc1c0aa233d]
[bt] (7) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(+0x3021211) [0x7fc1c0a91211]
[bt] (8) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::exec::GraphExecutor::InitArguments(nnvm::IndexedGraph const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, mxnet::Executor const*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*)+0xa0c) [0x7fc1c0a9567c]
[bt] (9) /gruntdata/zhimo.bmz/mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::string, nnvm::TShape, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, nnvm::TShape> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0x842) [0x7fc1c0a9dd42]

**Comment by phoenixbai** [comment]
it is gpu configuration problem.
closed.
