### ISSUE TITLE
distribute training

### ISSUE THREAD

**Issue by fanlu** [samsungsds-rnd/deepspeech.mxnet#5]
when I use launcher.py to training distributed
I got an error below
Traceback (most recent call last):
  File "main.py", line 327, in <module>
    do_training(args=args, module=module, data_train=data_train, data_val=data_val)
  File "/export/fanlu/deepspeech_zh_word_dist/train.py", line 166, in do_training
    module.save_checkpoint(prefix=get_checkpoint_path(args), epoch=n_epoch, save_optimizer_states=save_optimizer_states)
  File "/mxnet/python/mxnet/module/module.py", line 154, in save_checkpoint
    self.save_optimizer_states(state_name)
  File "/mxnet/python/mxnet/module/module.py", line 738, in save_optimizer_states
    self._kvstore.save_optimizer_states(fname)
  File "/mxnet/python/mxnet/kvstore.py", line 315, in save_optimizer_states
    assert self._updater is not None, "Cannot save states for distributed training"

**Comment by Soonhwan-Kwon** [comment]
option save_optimizer_states = True to False may help.
```
[train]
...
save_optimizer_states = False
...
```
But the checkpoint will loses the information of optimizer_states.
